# Example workflow
name: Cleanup and Build Website

on:
  push:
    branches:
      - master

jobs:

  formatting:
    name: Format Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/github-pages-deploy-action@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LANGUAGE: "java"
          MAKE_COMMAND: "make html"
          PAGES_BRANCH: "gh-pages"
          BUILD_FROM: "master"
          DOCS_FOLDER: "docs"
